apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-backup
  annotations:
    iam.gke.io/gcp-service-account: fleet-backup@testudo-dev.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: fleet-backup
    app.kubernetes.io/part-of: fleet
automountServiceAccountToken: true
