apiVersion: v1
kind: Service
metadata:
  name: fleet
  labels:
    app.kubernetes.io/name: fleet
    app.kubernetes.io/part-of: fleet
  annotations:
    cloud.google.com/backend-config: '{"default":"fleet-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fleet
  ports:
    - name: http
      port: 80
      targetPort: http

